services:
  api:
    image: mcr.microsoft.com/devcontainers/python:3.12
    working_dir: /workspace
    volumes:
      - ./:/workspace:cached
    command: sleep infinity
    environment:
      PG_DSN: postgresql+psycopg://postgres:postgres@db:5432/appsec
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appsec
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata:
